### ISSUE TITLE
最高値/最安値予測モデルのテクニカル特徴量調査

### ISSUE THREAD

**Issue by Masa-kuchii** [dondakeshimo/system-trading#20]
## 概要
最高値/最安値予測モデルで用いるテクニカル特徴量を決定する。

## 目的
予測精度の向上。

## 完了条件
実際にモデルで使用するテクニカル特徴量が本issueにまとめられ、
一人以上のレビュワーにより、本issueがクローズされる。

## 結論
signateファンダメンタルコンペのチュートリアル・上位解法を参考に、テクニカル特徴量を以下の通り、暫定的に決定した。

直近（1, 3, 5, 10, 20, 40, 60, 80, 120)における
各銘柄、日経平均、米国株(S&P500)の
- 終値の変化率（リターン）
- Average True range （ボラタリティー）
- Average True rangeの胴体部 （ボラタリティー）
- Average True rangeのヒゲ部 （ボラタリティー）
- 単純移動平均線からの乖離率
- （曜日や季節）

高値、安値予測では、ボラタリティーとトレンドを予測できる特徴量が重要となる。
ボラタリティー予測の特徴量としては、標準偏差や上記のATRがある。チュートリアルや3位解法では標準偏差が使われていたが、2位の専業シストレの方は標準偏差よりATRのほうがよいと述べている。実際に2位モデルの特徴量重要度はATRが占めており、また指標自体もATRのほうが強そうだったので、標準偏差ではなくATRを採用した。
トレンド予測の特徴量としては、signateコンペは決算発表日から20日間の高値/安値予測だったので、決算予想/実績やファンダメンタル指標が有効だった。しかしながら、今回は決算発表日に限定しない、かつ、ファンダメンタル情報はまだ使えないので、それらの代わりに、トレンド予測に効きそうな終値の変化率や単純移動平均線からの乖離率を入れている。
日経平均を入れている理由は、3位解法の安値予測に効いた特徴量として日経平均がかなり上位にあったため。
米国株（S&P500）は正直いらないかも？と思ったが、日本株は米国株に左右されるので、とりあえず入れている。
株価は季節性があるということだったので、（曜日や季節）の特徴量も暫定的に入れている。

## TODO
- 銘柄情報（権利確定日までの日数や配当）やファンダメンタル情報の特徴量追加

## 参考
[Google docリンク](https://docs.google.com/document/d/1FLY0O3WQr971oeooKL_GRgO-Cq49OU3BSiJUydkRsYU/edit?usp=sharing)
[signateチュートリアル](https://japanexchangegroup.github.io/J-Quants-Tutorial/#_%E3%83%87%E3%83%BC%E3%82%BF%E3%82%BB%E3%83%83%E3%83%88%E3%81%AE%E5%89%8D%E5%87%A6%E7%90%86)
[テクニカル指標まとめ](https://kabu.com/investment/guide/technical/01.html)

**Comment by Masa-kuchii** [comment]
@dondakeshimo , @IkuyaYamada 
レビューお願いします。

**Comment by dondakeshimo** [comment]
@Masa-kuchii 
特に問題ないと思います〜。
特徴量をそれに決めた理由はどこにも書いていないのでしょうか？

**Comment by Masa-kuchii** [comment]
@dondakeshimo 
コメントありがとうございます。
特徴量選定の理由を追記しましたので、再レビューお願いします。

**Comment by dondakeshimo** [comment]
OKです~

**Comment by Masa-kuchii** [comment]
ご確認ありがとうございます。
クローズします～
